### ISSUE TITLE
Binding constants in node v6

### ISSUE THREAD

**Issue by AngeIII** [tschaub/mock-fs#189]
There is an issue with binding constant on node v6
`var constants = require('constants');`

`console.log(constants.S_IFMT) === undefined`

In node v6 all that constants related to filesystem moved into fs namespace and can be reached by:
`constants.fs.S_IFMT`

Related to https://github.com/tschaub/mock-fs/blob/master/lib/binding.js

**Comment by tschaub** [comment]
@AngeIII - what do you get from the following:
```
node -e "console.log(require('constants').S_IFMT)"
```

On Node 4 - 7, I get `61440` from that.

It is true that the structure of `process.binding('constants')` changed.  But as of `mock-fs@3.10`, we are relying on `require('constants')` instead of `process.binding('constants')`.

Please reopen if you can provide an example of code that fails with Node 6.
