### ISSUE TITLE
"Use real fs" code slows tests down dramatically

### ISSUE THREAD

**Issue by kshay** [tschaub/mock-fs#192]
We recently noticed some of our unit tests had gotten much slower after upgrading some NPM dependencies. I tracked it down to upgrading mock-fs to ^3.11.0, specifically this commit:

https://github.com/tschaub/mock-fs/commit/61e0af1a

This seems to be a side effect of some kind, since we're only explicitly using mock-fs in one test file out of 25; the tests that run after that one become incredibly slow. The whole test suite runs in <30 seconds without this commit in place, and 7-8 minutes with it.

**Comment by kshay** [comment]
Thanks, I'll give it a try!

**Comment by geekflyer** [comment]
@tschaub Thanks, had the same problem and can confirm that mock-fs@beta fixes it. The tests are now much much faster.

Also I had before a problem / conflict which using the `mz/fs` module and `mock-fs`. Before I always had to require "mock-fs" before the first require of "mz/fs" , otherwise i could not properly mock "mz/fs" IO.

Thanks!

**Comment by jan-molak** [comment]
`mock-fs@4.0.0-beta.1` also fixes a compatibility issue between mock-fs and ts-node where node would freeze if a method on `fs` was invoked. Thanks @tschaub! 👍

**Comment by tschaub** [comment]
The `mock-fs@4` release is now out.
