### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by ryanblock** [tschaub/mock-fs#383]
Hi there! Like many folks, we rely on `mock-fs` – it's done an excellent job for us!

In [late October 2023 Node.js 20.x went into active LTS status](https://nodejs.org/en/blog/release/v20.9.0), making it the version recommended by most teams / companies to use. As we've seen in #380 and #382, 20.x has introduced issues with `mock-fs`. Unfortunately, these issues have not been spoken to, let alone remediated.

As an open source maintainer, I totally understand the myriad challenges related to maintaining a library like `mock-fs`. That said, I think it would be helpful to understand whether the primary maintainer (@tschaub) intends to continue work on this project so folks can make decisions on how to move forward.

Related: if you're looking for volunteers to delegate commit privileges I'd be happy to raise my hand, as I'm sure would be a few others around these parts.

💕🙏🏼

**Comment by 3cp** [comment]
Nodejs internal change does make it harder and harder for mock-fs to keep up.
#380 is probably fixable.
#382 belongs to a group of issues related to jest. Since jest also does monkey patching of Nodejs internals, it doesn't play well with mock-fs.

There is also #358, #319, we probably has no way to support it because Nodejs would not expose the new `fs_dir` binding.

In linked issue in #319, https://github.com/nodejs/node/issues/37746#issuecomment-798809618
Nodejs also planed to cut off `process.binding()` from user land, that's death sentence for mock-fs.

I started avoiding mock-fs on new projects. As a result, I am spending much less time on maintaining mock-fs. One technique I am using is to avoid direct calling of fs methods, create a wrapper file for fs, every other files are using my own version of `fs`. Then manually mock the limit usage in unit tests, if a logic only uses `readFile`, I only need to mock `readFile` call. When testing more parts together, I use tmp folder with real files.

**Comment by ryanblock** [comment]
A followup: after considering this thread for a couple days I opted to whip up a library that (mostly) clones `mock-fs`'s semantics while working with the actual filesystem in a tmp folder. As a nod to this project, I called it [`mock-tmp`](https://www.npmjs.com/package/mock-tmp).

It's still early days but so far it seems to be working alright thus far in the couple projects I've implemented it in this week. Unfortunately, I suspect it will lead to a small amount of business logic changes to accommodate the temp working dir, but I guess eventually that is to be expected when working with filesystem testing.

Anyway, thanks again to @tschaub and @3cp (and everyone else who's contributed) for all your work on this library, it's been so good for so long. 💕

**Comment by BadIdeaException** [comment]
> Nodejs internal change does make it harder and harder for mock-fs to keep up. #380 is probably fixable. #382 belongs to a group of issues related to jest. Since jest also does monkey patching of Nodejs internals, it doesn't play well with mock-fs.
> 
> There is also #358, #319, we probably has no way to support it because Nodejs would not expose the new `fs_dir` binding.
> 
> In linked issue in #319, [nodejs/node#37746 (comment)](https://github.com/nodejs/node/issues/37746#issuecomment-798809618) Nodejs also planed to cut off `process.binding()` from user land, that's death sentence for mock-fs.
> 
> I started avoiding mock-fs on new projects. As a result, I am spending much less time on maintaining mock-fs. One technique I am using is to avoid direct calling of fs methods, create a wrapper file for fs, every other files are using my own version of `fs`. Then manually mock the limited usage in unit tests, if a logic only uses `readFile`, I only need to mock `readFile` call. When testing more parts together, I use tmp folder with real files.

That is sad news, because I personally am finding mock-fs a lot easier to use than the main competitor, `memfs`. Shout out to @tschaub and @3cp here for the great work. :heart: 

I do wonder if [Customization hooks](https://nodejs.org/docs/latest/api/module.html#customization-hooks) (formerly known as loaders) might conceptually be a way to work around the missing `process.binding()`?
