### ISSUE TITLE
What would it take / would be possible to mock the fs for child_process spawns ?

### ISSUE THREAD

**Issue by kilianc** [tschaub/mock-fs#77]
for example:

```js
mock()
execSync('git init')
```

**Comment by voxpelli** [comment]
I'm thinking that something like https://github.com/mafintosh/fuse-bindings would be more appropriate then as this module mocks the node.js file system module rather than the file system itself while a fuse based approach could mount a fully mocked file system that eg. git and such could interact with.

**Comment by kilianc** [comment]
thanks!
